### ISSUE TITLE
GSOC Project: OpenMined-Android

### ISSUE THREAD

**Issue by adventuroussrv** [OpenMined/Roadmap#10]
### GSoC Project: OpenMined-Android

Mentor: @adventuroussrv

**Project Description:**

We are developing a Community App that will have the feature and information about the OpenMined Community and the It's Projects.
In this project, you will be implementing from scratch and will be working on the project adding more features.

**Required Skills:**

- Knowledge of Android Development with Kotlin
- Knowledge of Android Basics, Android UI, Data management, Firebase etc
- Familiarity (or willingness to become familiar) with OpenMined Projects and OpenMined Community 
- You are highly motivated and want to get involved in the project on a regular basis during the GSoC program

**Difficulty:** **Medium**

The main goal of this project is to make even more accessible to the community members to navigate through the organization & to get updates from the OpenMined Android App

**Comment by cereallarceny** [comment]
Seems like a great idea!

Could this be done as a React Native application instead so that we have support for Android and iOS out of the box?

**Comment by IamRavikantSingh** [comment]
I would like to work on this issue. Please mention which technology is final for working on the issue.
one point: for cross-platform app development please also give a thought on using flutter.

**Comment by cereallarceny** [comment]
Please hold off for now @IamRavikantSingh.  We haven't chosen the final priority of issues for GSOC.

**Comment by avinath1998** [comment]
Hey, what about doing this project using Flutter, that way, you can have multiple different platforms, including web and iOS using a single codebase instead of just Android. (I'm applying for this for GSOC).

**Comment by cereallarceny** [comment]
As I mentioned above, we could use React Native.  We don't use Flutter in our codebase and will have a component system built in React.

**Comment by cereallarceny** [comment]
As I mentioned above, we could use React Native.  We don't use Flutter in our codebase and will have a component system built in React.

**Comment by thelosergeek** [comment]
I am interested in the project. Also, whose firebase account are we going to use?

**Comment by cereallarceny** [comment]
@thelosergeek Mine or one of an OpenMined admin.

**Comment by cereallarceny** [comment]
@thelosergeek If you're an Android dev, send me a DM on Slack. I may have a project for you in the meantime.

**Comment by thelosergeek** [comment]
@cereallarceny Sure!

**Comment by thelosergeek** [comment]
Check your DM

**Comment by adventuroussrv** [comment]
Hey everyone! If you are new OpenMined Join the Slack Community [here](http://slack.openmined.org/) and the #gsoc channel!

also, I encourage you to contribute to the projects, if you are beginner check out the [good first issue](https://github.com/search?q=user%3AOpenMined+label%3A%22good+first+issue%22+state%3Aopen&type=Issues&ref=advsearch&l=&l=)
